### ISSUE TITLE
Verbindet sich etwas zu oft?

### ISSUE THREAD

**Issue by hugo419752** [iobroker-community-adapters/ioBroker.boschindego#49]
Hi,

ich bin echt begeistert von dem Adapter, aber der verbindungsaubau findet m.M.n. zu oft statt.

boschindego.0 | 2024-05-11 11:19:09.425 | info | Found 1 devices
boschindego.0 | 2024-05-11 11:19:08.791 | info | Login successful
boschindego.0 | 2024-05-11 11:19:04.600 | info | Login to Bosch Indego
boschindego.0 | 2024-05-11 11:19:04.421 | info | starting. Version 1.2.0 in /opt/iobroker/node_modules/iobroker.boschindego, node: v18.20.2, js-controller: 5.0.19
boschindego.0 | 2024-05-11 11:19:00.554 | info | terminating
boschindego.0 | 2024-05-11 11:19:00.064 | info | Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
boschindego.0 | 2024-05-11 11:19:00.060 | info | terminating
boschindego.0 | 2024-05-11 11:19:00.045 | info | Scheduled restart.
boschindego.0 | 2024-05-11 11:18:09.625 | info | Found 1 devices
boschindego.0 | 2024-05-11 11:18:08.948 | info | Login successful
boschindego.0 | 2024-05-11 11:18:04.734 | info | Login to Bosch Indego
boschindego.0 | 2024-05-11 11:18:04.552 | info | starting. Version 1.2.0 in /opt/iobroker/node_modules/iobroker.boschindego, node: v18.20.2, js-controller: 5.0.19
boschindego.0 | 2024-05-11 11:18:00.559 | info | terminating
boschindego.0 | 2024-05-11 11:18:00.067 | info | Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
boschindego.0 | 2024-05-11 11:18:00.062 | info | terminating
boschindego.0 | 2024-05-11 11:18:00.047 | info | Scheduled restart.
boschindego.0 | 2024-05-11 11:17:09.925 | info | Found 1 devices
boschindego.0 | 2024-05-11 11:17:08.726 | info | Login successful
boschindego.0 | 2024-05-11 11:17:04.639 | info | Login to Bosch Indego
boschindego.0 | 2024-05-11 11:17:04.459 | info | starting. Version 1.2.0 in /opt/iobroker/node_modules/iobroker.boschindego, node: v18.20.2, js-controller: 5.0.19
boschindego.0 | 2024-05-11 11:17:00.529 | info | terminating
boschindego.0 | 2024-05-11 11:17:00.030 | info | Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
boschindego.0 | 2024-05-11 11:17:00.028 | info | terminating
boschindego.0 | 2024-05-11 11:17:00.020 | info | Scheduled restart.

Jede Minute findet eine neue Verbindung statt. Sogar mein Iobroker meckert schon.
Ist das so gewollt, oder habe ich ein Problem? 

Wäre es zudem noch möglich die Befehle an den Roboter von true/false auf "Buttons" zu ändern?

Besten Gruß

Martin

**Comment by hugo419752** [comment]
Done

**Comment by mcm1957** [comment]
Which release do ypou use?
Did'nt see a notice at the changelog related to this problem.
