### ISSUE TITLE
Login is not work anymore

### ISSUE THREAD

**Issue by jbeenenga** [iobroker-community-adapters/ioBroker.boschindego#73]
**Describe the bug**  
While start of the adapter, an error is shown, that a request received a 404 response. So no loing is possible. 
After short analyse, the problem should be at the POST call of https://prodindego.b2clogin.com/prodindego.onmicrosoft.com/oauth2/authresp. Does anyone knows whether the path has been changed?
**To Reproduce**  
1. Start the adapter
2. Look into logs
3. An 404 error will be logged
**Expected behavior**  
Login works again.

**Screenshots & Logfiles**  

**Versions:**  
 - Adapter version: 1.2.0
 - JS-Controller version: 6.0.11
 - Node version: 18.20.4
 - Operating system: ubuntu

**Additional context**

**Comment by real-easy** [comment]
kann ich bestätigen, login mit dem adapter schlägt fehl, während die app ohne update auf dem handy noch funktioniert.

vor einem monat (13.09.2024) kahm eine mail in der eine umstellung beschrieben wurde.

hier der inhalt:

```
SingleKey ID - Anbieterwechsel innerhalb der Bosch Gruppe

Aufgrund von konzerninternen Änderungen wird die SingleKey ID ab sofort nicht mehr von der Bosch.IO GmbH, sondern von der Robert Bosch GmbH zur Verfügung gestellt.
```

details wurden natürlich nicht genannt.


hier ein auszung aus meiner log:

```
boschindego.1
9864	2024-10-14 21:28:49.385	error	{"errors":[{"message":"Cannot convert access token to JSON"}]}

boschindego.1
9864	2024-10-14 21:28:49.384	error	AxiosError: Request failed with status code 401

boschindego.1
9864	2024-10-14 21:28:03.996	error	undefined

boschindego.1
9864	2024-10-14 21:28:03.996	error	Could not extract login params

boschindego.1
9864	2024-10-14 21:28:03.996	error	Error: getaddrinfo ENOENT p36.authz.bosch.com

boschindego.1
9864	2024-10-14 21:28:02.975	info	Login to Bosch Indego
```

**Comment by ElRedef** [comment]
Hello together,,

on my side everything works still fine. But i havent restarted the adapter.  And now i don't want to do that :-)

I'm also on 1.2.0.

**Comment by DEV2DEV-DE** [comment]
Ich kann das Verhalten bestätigen.
```
2024-10-15 08:00:03.824 - error: boschindego.0 (3735386) AxiosError: Request failed with status code 404
2024-10-15 08:00:03.824 - error: boschindego.0 (3735386) "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."
```

**Comment by real-easy** [comment]
so nachdem ich in meinem pihole die **p36.authz.bosch.com** freigegeben habe sieht meine log nun auch so aus:
```

boschindego.1 | 9348 | 2024-10-15 16:52:50.845 | error | {"errors":[{"message":"Cannot convert access token to JSON"}]}
-- | -- | -- | -- | --
boschindego.1 | 9348 | 2024-10-15 16:52:50.845 | error | AxiosError: Request failed with status code 401
boschindego.1 | 9348 | 2024-10-15 16:52:49.342 | error | {"errors":[{"message":"Cannot convert access token to JSON"}]}
boschindego.1 | 9348 | 2024-10-15 16:52:49.342 | error | AxiosError: Request failed with status code 401
boschindego.1 | 9348 | 2024-10-15 16:52:05.841 | error | "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."
boschindego.1 | 9348 | 2024-10-15 16:52:05.840 | error | AxiosError: Request failed with status code 404
boschindego.1 | 9348 | 2024-10-15 16:52:03.063 | info | Login to Bosch Indego
boschindego.1 | 9348 | 2024-10-15 16:52:02.996 | info | starting. Version 1.2.0 (non-npm: iobroker-community-adapters/ioBroker.boschindego) in C:/iobroker/HausAutoB2022/node_modules/iobroker.boschindego, node: v18.19.1, js-controller: 5.0.19

```

**Comment by real-easy** [comment]
nochmal ein update, wenig hilfreich aber evtl. für den ein oder anderen informativ.
der adapter von openhab funktioniert leider auch nicht mehr. hier error 403.

**Comment by TA2k** [comment]
v1.2.1
